//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace My_CV.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_CvEntities2 : DbContext
    {
        public DB_CvEntities2()
            : base("name=DB_CvEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBL_Admin> TBL_Admin { get; set; }
        public virtual DbSet<TBL_Deneyimler> TBL_Deneyimler { get; set; }
        public virtual DbSet<TBL_Egitim> TBL_Egitim { get; set; }
        public virtual DbSet<TBL_Hakkımda> TBL_Hakkımda { get; set; }
        public virtual DbSet<TBL_Hobiler> TBL_Hobiler { get; set; }
        public virtual DbSet<TBL_Iletisim> TBL_Iletisim { get; set; }
        public virtual DbSet<TBL_Projeler> TBL_Projeler { get; set; }
        public virtual DbSet<TBL_Sertifika> TBL_Sertifika { get; set; }
        public virtual DbSet<TBL_Yetenekler> TBL_Yetenekler { get; set; }
    }
}
