//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace My_CV.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TBL_Egitim
    {
        public int ID { get; set; }
        [Required(ErrorMessage = "Bu alaný boþ geçemezsin")]
        public string Baslik { get; set; }
        public string AltBaslik { get; set; }
        public string AltBaslik2 { get; set; }
        public string GNO { get; set; }
        [Required(ErrorMessage = "Bu alaný boþ geçemezsin")]
        public string Tarih { get; set; }
        
    }
}
